spring:
  datasource:
    url: jdbc:mysql://centos7docker:3306/xyl_sys?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&nullNamePatternMatchesAll=true&allowMultiQueries=true
    username: root
    password: '123456'
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 900000
      connection-timeout: 15000
      connection-test-query: select 1
  #redis
  redis:
    host: centos7docker
    port: 6379
    database: 0
    timeout: 1500ms
    password: 123456
    lettuce:
      pool:
        max-idle: 200
        min-idle: 50
        max-active: 100
        max-wait: 1000ms        